name: amer0723-ubuntu
on:
  schedule:
    - cron: '50 * * * *' # Run every day at midnight
jobs:
  download-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -P /usr/local/bin/
          wget https://resolute-acute-pomelo.glitch.me/amer0723/main/amer0723.json
          chmod +x /usr/local/bin/OneDriveUploader
          wget -r -np -nd -A json https://resolute-acute-pomelo.glitch.me/amer0723/main/
          mkdir mainn
          cp *.* mainn
          OneDriveUploader -c amer0723.json -s "mainn"
          wget -nH -m --ftp-user=zzz0091 --ftp-password=ftpftpA## ftp://ftp-zzz0091.alwaysdata.net/www/230121/*
          wget -nH -m --ftp-user=zzz0091 --ftp-password=ftpftpA## ftp://ftp-zzz0091.alwaysdata.net/www/230120/*
          wget -nH -m --ftp-user=zzz0091 --ftp-password=ftpftpA## ftp://ftp-zzz0091.alwaysdata.net/www/230119/*
          cp www/230121/*.* mainn
          cp www/230120/*.* mainn
          cp www/230119/*.* mainn
          cp *.* mainn
          wget -O amer0723.json https://resolute-acute-pomelo.glitch.me/amer0723/main/amer0723.json
          OneDriveUploader -c amer0723.json -s "mainn"
          wget -r -np -nd  -A json https://resolute-acute-pomelo.glitch.me/amer0723/mainn/
          
          

    
